import {CountryFlagData} from './type';


export const data: CountryFlagData[] = [
  {
    group: 'americas',
    country: 'United States',
    countryId: 'unitedstates',
    currency: 'USD',
    emoji: '\uD83C\uDDFA\uD83C\uDDF8',
  },
  {
    group: 'americas',
    country: 'Canada',
    countryId: 'canada',
    currency: 'CAD',
    emoji: '\uD83C\uDDE8\uD83C\uDDE6',
  },
  {
    group: 'americas',
    country: 'Mexico',
    countryId: 'mexico',
    currency: 'MXN',
    emoji: '\uD83C\uDDF2\uD83C\uDDFD',
  },
  {
    group: 'americas',
    country: 'Brazil',
    countryId: 'brazil',
    currency: 'BRL',
    emoji: '\uD83C\uDDE7\uD83C\uDDF7',
  },
  {
    group: 'americas',
    country: 'Colombia',
    countryId: 'colombia',
    currency: 'COP',
    emoji: '\uD83C\uDDE8\uD83C\uDDF4',
  },
  {
    group: 'euro-area',
    country: 'Euro Area',
    countryId: 'euroarea',
    currency: 'EUR',
    emoji: '\uD83C\uDDEA\uD83C\uDDFA',
  },
  {
    group: 'euro-area',
    country: 'Germany',
    countryId: 'germany',
    currency: 'EUR',
    emoji: '\uD83C\uDDE9\uD83C\uDDEA',
  },
  {
    group: 'euro-area',
    country: 'France',
    countryId: 'france',
    currency: 'EUR',
    emoji: '\uD83C\uDDEB\uD83C\uDDF7',
  },
  {
    group: 'euro-area',
    country: 'Spain',
    countryId: 'spain',
    currency: 'EUR',
    emoji: '\uD83C\uDDEA\uD83C\uDDF8',
  },
  {
    group: 'euro-area',
    country: 'Italy',
    countryId: 'italy',
    currency: 'EUR',
    emoji: '\uD83C\uDDEE\uD83C\uDDF9',
  },
  {
    group: 'euro-area',
    country: 'Greece',
    countryId: 'greece',
    currency: 'EUR',
    emoji: '\uD83C\uDDEC\uD83C\uDDF7',
  },
  {
    group: 'euro-area',
    country: 'Austria',
    countryId: 'austria',
    currency: 'EUR',
    emoji: '\uD83C\uDDE6\uD83C\uDDF9',
  },
  {
    group: 'euro-area',
    country: 'Ireland',
    countryId: 'ireland',
    currency: 'EUR',
    emoji: '\uD83C\uDDEE\uD83C\uDDEA',
  },
  {
    group: 'euro-area',
    country: 'Finland',
    countryId: 'finland',
    currency: 'EUR',
    emoji: '\uD83C\uDDEB\uD83C\uDDEE',
  },
  {
    group: 'euro-area',
    country: 'Netherlands',
    countryId: 'netherlands',
    currency: 'EUR',
    emoji: '\uD83C\uDDF3\uD83C\uDDF1',
  },
  {
    group: 'euro-area',
    country: 'Portugal',
    countryId: 'portugal',
    currency: 'EUR',
    emoji: '\uD83C\uDDF5\uD83C\uDDF9',
  },
  {
    group: 'euro-area',
    country: 'Belgium',
    countryId: 'belgium',
    currency: 'EUR',
    emoji: '\uD83C\uDDE7\uD83C\uDDEA',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'European Union',
    countryId: 'europeanunion',
    currency: 'EUR',
    emoji: '\uD83C\uDDEA\uD83C\uDDFA',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Czech Republic',
    countryId: 'czechrepublic',
    currency: 'CZK',
    emoji: '\uD83C\uDDE8\uD83C\uDDFF',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Denmark',
    countryId: 'denmark',
    currency: 'DKK',
    emoji: '\uD83C\uDDE9\uD83C\uDDF0',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'United Kingdom',
    countryId: 'unitedkingdom',
    currency: 'GBP',
    emoji: '\uD83C\uDDEC\uD83C\uDDE7',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Sweden',
    countryId: 'sweden',
    currency: 'SEK',
    emoji: '\uD83C\uDDF8\uD83C\uDDEA',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Switzerland',
    countryId: 'switzerland',
    currency: 'CHF',
    emoji: '\uD83C\uDDE8\uD83C\uDDED',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Poland',
    countryId: 'poland',
    currency: 'PLN',
    emoji: '\uD83C\uDDF5\uD83C\uDDF1',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Russia',
    countryId: 'russia',
    currency: 'RUB',
    emoji: '\uD83C\uDDF7\uD83C\uDDFA',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Norway',
    countryId: 'norway',
    currency: 'NOK',
    emoji: '\uD83C\uDDF3\uD83C\uDDF4',
  },
  {
    group: 'non-euro-zone-europe',
    country: 'Hungary',
    countryId: 'hungary',
    currency: 'HUF',
    emoji: '\uD83C\uDDED\uD83C\uDDFA',
  },
  {
    group: 'asia-pacific',
    country: 'Japan',
    countryId: 'japan',
    currency: 'JPY',
    emoji: '\uD83C\uDDEF\uD83C\uDDF5',
  },
  {
    group: 'asia-pacific',
    country: 'Australia',
    countryId: 'australia',
    currency: 'AUD',
    emoji: '\uD83C\uDDE6\uD83C\uDDFA',
  },
  {
    group: 'asia-pacific',
    country: 'New Zealand',
    countryId: 'newzealand',
    currency: 'NZD',
    emoji: '\uD83C\uDDF3\uD83C\uDDFF',
  },
  {
    group: 'asia-pacific',
    country: 'China',
    countryId: 'china',
    currency: 'CNY',
    emoji: '\uD83C\uDDE8\uD83C\uDDF3',
  },
  {
    group: 'asia-pacific',
    country: 'India',
    countryId: 'india',
    currency: 'INR',
    emoji: '\uD83C\uDDEE\uD83C\uDDF3',
  },
  {
    group: 'asia-pacific',
    country: 'South Korea',
    countryId: 'southkorea',
    currency: 'KRW',
    emoji: '\uD83C\uDDF0\uD83C\uDDF7',
  },
  {
    group: 'asia-pacific',
    country: 'Thailand',
    countryId: 'thailand',
    currency: 'THB',
    emoji: '\uD83C\uDDF9\uD83C\uDDED',
  },
  {
    group: 'asia-pacific',
    country: 'Singapore',
    countryId: 'singapore',
    currency: 'SGD',
    emoji: '\uD83C\uDDF8\uD83C\uDDEC',
  },
  {
    group: 'asia-pacific',
    country: 'Hong Kong',
    countryId: 'hongkong',
    currency: 'HKD',
    emoji: '\uD83C\uDDED\uD83C\uDDF0',
  },
  {
    group: 'asia-pacific',
    country: 'Taiwan',
    countryId: 'taiwan',
    currency: 'TWD',
    emoji: '\uD83C\uDDF9\uD83C\uDDFC',
  },
  {
    group: 'asia-pacific',
    country: 'Indonesia',
    countryId: 'indonesia',
    currency: 'IDR',
    emoji: '\uD83C\uDDEE\uD83C\uDDE9',
  },
  {
    group: 'asia-pacific',
    country: 'Philippines',
    countryId: 'philippines',
    currency: 'PHP',
    emoji: '\uD83C\uDDF5\uD83C\uDDED',
  },
  {
    group: 'middle-east-africa',
    country: 'Israel',
    countryId: 'israel',
    currency: 'ILS',
    emoji: '\uD83C\uDDEE\uD83C\uDDF1',
  },
  {
    group: 'middle-east-africa',
    country: 'South Africa',
    countryId: 'southafrica',
    currency: 'ZAR',
    emoji: '\uD83C\uDDFF\uD83C\uDDE6',
  },
];
