pool:
  vmImage: windows-latest
  demands:
    # These are needed for building `@newrelic/native-metrics` dependency
    - msbuild
    - visualstudio

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

trigger:
  paths:
    include:
      - kl-web-common/*
      - kl-ui/*

stages:
- stage: Lint

  jobs:
    - job: Lint

      steps:
      - template: templates/checkout-and-cache.yml

      - script: yarn run lint
        displayName: 'Lint Source'
        workingDirectory: ./$(APP_FOLDER_NAME)

      - script: yarn run lint:css
        displayName: 'Lint CSS'
        workingDirectory: ./$(APP_FOLDER_NAME)

- stage: BuildDeploy
  displayName: Build & Deploy

  dependsOn:
    - Lint

  jobs:
    - job: Build

      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run build
          displayName: 'Build App'
          workingDirectory: ./$(APP_FOLDER_NAME)
          env:
            NODE_ENV: production

        - task: CopyFiles@2
          displayName: 'Copy Dependencies'
          inputs:
            SourceFolder: ./node_modules
            Contents: '**'
            TargetFolder: ./$(APP_FOLDER_NAME)/node_modules
            OverWrite: true

        - task: ArchiveFiles@2
          displayName: 'Archive Build'

          inputs:
            rootFolderOrFile: ./$(APP_FOLDER_NAME)
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'

- stage: Test

  dependsOn: []

  jobs:
    - job: Jest
      displayName: 'Run Jest Tests / Coverage'

      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run test:ci
          workingDirectory: ./$(APP_FOLDER_NAME)
          displayName: 'Run jest Tests'

        - task: PowerShell@2
          displayName: 'Upload Coverage (Codacy)'
          env:
            CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)
          inputs:
            targetType: 'inline'
            workingDirectory: ./$(APP_FOLDER_NAME)
            script: |
              $LatestVersion = "$(Invoke-WebRequest -URI https://artifacts.codacy.com/bin/codacy-coverage-reporter/latest)"
              
              Invoke-WebRequest `
                -URI "https://artifacts.codacy.com/bin/codacy-coverage-reporter/$LatestVersion/codacy-coverage-reporter-assembly.jar" `
                -OutFile codacy-coverage-reporter-assembly.jar
              java -jar codacy-coverage-reporter-assembly.jar `
                report `
                -r clover.xml `
                -t ${env:CODACY_PROJECT_TOKEN}

        - task: PublishCodeCoverageResults@1
          displayName: 'Upload Coverage (Azure)'
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: ./$(APP_FOLDER_NAME)/cobertura-coverage.xml
            failIfCoverageEmpty: true

        - task: PublishTestResults@2
          displayName: 'Upload Test Results (Azure)'
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'junit.xml'
            searchFolder: ./$(Pipeline.Workspace)/s/$(APP_FOLDER_NAME)
            failTaskOnFailedTests: true
            testRunTitle: 'Jest Tests'
