pool:
  vmImage: windows-latest
  demands:
    # These are needed for building `@newrelic/native-metrics` dependency
    - msbuild
    - visualstudio

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

stages:
- stage: Lint

  jobs:
    - job: Lint

      steps:
      - template: templates/checkout-and-cache.yml

      - script: yarn run lint
        displayName: 'Lint TypeScript'
        workingDirectory: ./$(APP_FOLDER_NAME)

- stage: Build

  dependsOn:
    - Lint

  jobs:
    - job: Build

      steps:
        - template: templates/checkout-and-cache.yml

        - task: Cache@2
          displayName: 'Cache Built Source'
          inputs:
            key: 'build | "$(Agent.OS)" | "$(Build.BuildNumber)"'
            path: '$(Pipeline.Workspace)/s'

        - script: yarn run build
          displayName: 'Build Common Module'
          workingDirectory: ./$(APP_COMMON_MODULE_FOLDER_NAME)
          env:
            NODE_ENV: production

        - task: CopyFiles@2
          displayName: 'Copy Common Module Dist'
          inputs:
            SourceFolder: ./$(APP_COMMON_MODULE_FOLDER_NAME)/dist
            Contents: '**'
            TargetFolder: ./$(APP_FOLDER_NAME)/node_modules/$(APP_COMMON_MODULE_FOLDER_NAME)
            OverWrite: true

        - script: yarn run build
          displayName: 'Build App'
          workingDirectory: ./$(APP_FOLDER_NAME)
          env:
            NODE_ENV: production

        - task: CopyFiles@2
          displayName: 'Copy Proto'
          inputs:
            SourceFolder: ./$(APP_FOLDER_NAME)/src/protos
            Contents: '**'
            TargetFolder: ./$(APP_FOLDER_NAME)/dist/protos
            OverWrite: true

        - task: CopyFiles@2
          displayName: 'Copy dependencies from workspace'
          inputs:
            SourceFolder: ./node_modules
            Contents: '**'
            TargetFolder: ./$(APP_FOLDER_NAME)/node_modules
            OverWrite: true

- stage: Deploy

  dependsOn:
    - Lint
    - Build

  jobs:
    - job: Deploy

      steps:
        - template: templates/checkout-and-cache.yml

        - task: Cache@2
          displayName: 'Cache Built Source'
          inputs:
            key: 'build | "$(Agent.OS)" | "$(Build.BuildNumber)"'
            path: '$(Pipeline.Workspace)/s'

        - task: ArchiveFiles@2
          displayName: 'Archive Build Artifacts'

          inputs:
            rootFolderOrFile: ./$(APP_FOLDER_NAME)
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Build Artifacts'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'
